### ISSUE TITLE
Error 403 - Validierung vom CSRF-Token ist fehlgeschlagen

### ISSUE THREAD

**Issue by suN1506** [pfefferf/grunt-nwabap-ui5uploader#12]
Hi,

im trying to upload my Sources but i got this error:

````
Warning: Error: got 403 response (CSRF-Token-Validierung ist fehlgeschlagen) Use --force to continue.

Aborted due to warnings.

Process finished with exit code 6
````

this is my Task Config:

```
nwabap_ui5uploader: {
            options: {
                conn: {
                    server: sHost,
                    client: sClient
                },
                auth: {
                    user: sUser,
                    pwd: sPwd
                }
            },
            upload_build: {
                options: {
                    ui5: {
                        language : 'DE',
                        calc_appindex: true,
                        package : sPackage,
                        bspcontainer: sAppNameSAP,
                        bspcontainer_text: sAppDesc,
                        transportno : sTransportNo
                    },
                    resources: {
                        cwd: tmpDir,
                        src: '**/*.*'
                    }
                }
            }
        },
```

any ideas what went wrong, or how to fix this?

Thanks! :)

**Comment by pfefferf** [comment]
It seems that the CSRF Token cannot be determined because of any reason. The CSRF Token is necessary to make secured PUT/POST requests.

Unfortunately the coding did not forward any errors occurred in the CSRF Token determination request. I fixed that with version 0.1.17. Please install the new version and check if you get in the log more details about the root cause why the CSRF Token determination fails.

Thx.

**Comment by suN1506** [comment]
hi thanks for the fast response. :)

unfortunately im already using Version 0.1.17

here is a Log i got by using "--verbose" parameter:

`
```
Running "nwabap_ui5uploader:upload_build" (nwabap_ui5uploader) task
Verifying property nwabap_ui5uploader.upload_build exists in config...OK
File: [no files]
Options: resources={"cwd":"../dist/sources","src":"**/*.*"}, conn={"server":"<serverURL>","client":"100"}, auth={"user":"<userName>","pwd":"<userPwd>"}, ui5={"language":"DE","calc_appindex":true,"package":"<package>","bspcontainer":"<bspContainer>","bspcontainer_text":"<description>","transportno":"<TA_Number>"}
Options: {"resources":{"cwd":"../dist/sources","src":"**/*.*"},"conn":{"server":"<serverURL>","client":"100","useStrictSSL":true},"auth":{"user":"<userName>","pwd":"<userPwd>"},"ui5":{"language":"DE","calc_appindex":true,"package":"<package>","bspcontainer":"<bspContainer>","bspcontainer_text":"<description>","transportno":"<TA_Number>"}}
Files: 
Artifacts to Sync:  [ { type: 'file',
    id: '/Component-dbg.js',
    modif: 'delete',
    levelCount: 1 },
  { type: 'file',
    id: '/Component-preload-dbg.js',
    modif: 'delete',
    levelCount: 1 },
  { type: 'file',
    id: '/Component-preload.js',
    modif: 'delete',
    levelCount: 1 },
  { type: 'file',
    id: '/Component.js',
    modif: 'delete',
    levelCount: 1 },
  { type: 'folder',
    id: '/META-INF',
    modif: 'delete',
    levelCount: 1 },
  { type: 'folder', id: '/WEB-INF', modif: 'delete', levelCount: 1 },
  { type: 'folder',
    id: '/controller',
    modif: 'delete',
    levelCount: 1 },
  { type: 'folder', id: '/css', modif: 'delete', levelCount: 1 },
  { type: 'folder',
    id: '/fragments',
    modif: 'delete',
    levelCount: 1 },
  { type: 'folder', id: '/i18n', modif: 'delete', levelCount: 1 },
  { type: 'folder', id: '/img', modif: 'delete', levelCount: 1 },
  { type: 'file',
    id: '/index.html',
    modif: 'delete',
    levelCount: 1 },
  { type: 'file',
    id: '/manifest.json',
    modif: 'delete',
    levelCount: 1 },
  { type: 'folder', id: '/model', modif: 'delete', levelCount: 1 },
  { type: 'folder', id: '/scripts', modif: 'delete', levelCount: 1 },
  { type: 'folder', id: '/view', modif: 'delete', levelCount: 1 },
  { type: 'file',
    id: '/META-INF/MANIFEST.MF',
    modif: 'delete',
    levelCount: 2 },
  { type: 'folder',
    id: '/WEB-INF/lib',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/WEB-INF/web.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/App-dbg.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/App.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/BaseController-dbg.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/BaseController.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/Detail-dbg.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/Detail.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/Empty-dbg.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/Empty.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/ErrorHandler-dbg.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/ErrorHandler.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/Master-dbg.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/Master.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/Overview-dbg.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/Overview.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/notFound-dbg.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/controller/notFound.controller.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/css/intro-minified-dbg.css',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/css/intro-minified.css',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/css/introjs-nazanin-dbg.css',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/css/introjs-nazanin.css',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/css/introjs-royal-dbg.css',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/css/introjs-royal.css',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/css/style-dbg.css',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/css/style.css',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/fragments/aktivitaeten.fragment.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/fragments/aktivitaetenDialog.fragment.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/fragments/dayOptions.fragment.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/fragments/settings.fragment.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/fragments/tagesdaten.fragment.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/fragments/uebersicht.fragment.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/i18n/i18n.properties',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/i18n/i18n_de.properties',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/i18n/i18n_de_DE.properties',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/img/logo_120.png',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/img/logo_60.png',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/img/logo_76.png',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/model/formatter-dbg.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/model/formatter.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/model/models-dbg.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/model/models.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/scripts/intro-minified-dbg.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/scripts/intro-minified.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/scripts/moment-dbg.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/scripts/moment.js',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/view/App.view.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/view/Detail.view.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/view/Empty.view.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/view/Master.view.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/view/Overview.view.xml',
    modif: 'delete',
    levelCount: 2 },
  { type: 'file',
    id: '/view/notFound.view.xml',
    modif: 'delete',
    levelCount: 2 } ]
Warning: Error: got 403 response (CSRF-Token-Validierung ist fehlgeschlagen) Use --force to continue.

Aborted due to warnings.

Process finished with exit code 6
```
`

any other ideas?

**Comment by pfefferf** [comment]
Just published 0.1.17. So your original post cannot be based on 0.1.17 but on 0.1.16.

**Comment by suN1506** [comment]
i updated the module just before my post and tested it.. i see version in package.json is 0.1.17 but output is still the same.

**Comment by pfefferf** [comment]
Then the CSRF token determination is successful. Try to check the ICF logs on the server.

**Comment by suN1506** [comment]
Figured out that the Problem just exists when im using an Reverse Proxy for connection to the SAP-System.

Any idea why this causes a Problem? 

Thanks for the help!

**Comment by pfefferf** [comment]
How your reverse proxy handles request/reponse headers? The CSRF Token is retrieved and transferred via header X-CSRF-Token. If the reverse proxy has e.g. a white-list implementation maybe the header is not transferred.

**Comment by suN1506** [comment]
Hm.. after investigating the Apache Configuration i didn't found a solution. There is no change at the header propertys just the ProxyPass to the SAP-System..

I mean, it works all fine when using a UI5 App.. 
There im able to fetch an CSRF Token and see the Token in Response Header. Header-Field is: "x-csrf-token"

**Comment by suN1506** [comment]
did some further investigations. It seems that the reverse proxy is wrong configurated. It is not forwarding the %2F (encoded slashes) correctly. So this is clearly not an fault caused by this grunt task.

Im closing this now.
Thanks for your help!
